export const paths = {
    index: '/',
    home: '/home',
    products: '/products',
    users: '/users',
    product: '/product',
    params: '/params',
    sale: '/sale',
    sales: '/sales',
    loggout: '/loggout',
    landingpage: '/landingpage',
    checkout: '/checkout',
    signup: '/signup',
    login: '/login',
};